### ISSUE TITLE
Postgres: relate bails on date query

### ISSUE THREAD

**Issue by Fristi** [lucidsoftware/relate#44]
`sql"SELECT session_id, user_uuid, device_uuid FROM sessions WHERE session_id = $sessionId AND AGE(now(), created_at) < interval '${sessionDuration.toMillis.toString} milliseconds'"`

throws a exception

`Caused by: org.postgresql.util.PSQLException: The column index is out of range: 2, number of columns: 1`

**Comment by gregghz** [comment]
Could you possibly write this same query using raw JDBC? I'm not very familiar with postgres and I'm not 100% sure how this query should look.

**Comment by Fristi** [comment]
I also tried this:

```scala
  implicit def fromFiniteDuration(state: FiniteDuration): SingleParameter =
    new StringParameter(s"${state.toMinutes} minutes")

      val stmt = sql"SELECT session_id, user_uuid, device_uuid FROM sessions WHERE session_id = $sessionId AND AGE(now(), created_at) <= interval $sessionDuration"
      println(s"sql: ${stmt.statementString}")

        stmt
        .asList(decoder)
        .headOption

```

Which throws

```
sql: HikariProxyPreparedStatement@61506193 wrapping SELECT session_id, user_uuid, device_uuid FROM sessions WHERE session_id = '$2a$10$ES/P9qy1TrAuah7dVuZEeehL/oeVJ5Sm/WSFYh0JO4AfL04SjyKg.' AND AGE(now(), created_at) <= interval '5 minutes'
[ERROR][17:09:20.676][application][C:] -

! @736ajg8kd - Internal server error, for (POST) [/api/v0.1/user/exchange] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PSQLException: ERROR: syntax error at or near "$2"
  Position: 118]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by gregghz** [comment]
The easiest work around I know of is to leverage PGInterval from the postgres driver:

```
implicit class PGIntervalParameter(value: PGInterval) extends SingleParameter {
  protected def set(stmt: PreparedStatement, i: Int) = stmt.setObject(i, value)
}

// ...

val interval = new PGInterval(s"${sessionDuration.toMillis} milliseconds")
sql"SELECT session_id, user_uuid, device_uuid FROM sessions WHERE session_id = $sessionId AND AGE(now(), created_at) < $interval"
```

Building on your FiniteDuration example you could do this:

```
implicit def fromFiniteDuration(state: FiniteDuration): SingleParameter =
    new PGIntervalParameter(new PGInterval(s"${state.toMillis} milliseconds"))
```

I think it would make sense to create a postgres sub-project and add the PGIntervalParameter to that so that it can be optionally imported. I'm not 100% sure what that sub-project looks like yet and I'm curious what over data types we need to deal with for postgres. I know there are a lot of different types it supports that MySQL doesn't but I don't have a good feel for what they are.

**Comment by Fristi** [comment]
I've tried to use this:

```scala
private class PGIntervalParameter(value: PGInterval) extends SingleParameter {
    protected def set(stmt: PreparedStatement, i: Int) = stmt.setObject(i, value)
  }

  private class PGUUIDParameter(value: UUID) extends SingleParameter {
    protected def set(stmt: PreparedStatement, i: Int) = stmt.setObject(i, value)
  }

  private implicit class FiniteDurationParameter(value: FiniteDuration) extends PGIntervalParameter(new PGInterval(s"${value.toSeconds} seconds"))

  private implicit class UUIDParameter(value: UUID) extends PGUUIDParameter(value)
```

Query:

```scala
    val stmt = sql"SELECT session_id, user_uuid, device_uuid FROM sessions WHERE session_id = $sessionId AND AGE(now(), created_at) < interval $sessionDuration"

    println(s"statement: ${stmt.statementString}")

    stmt
      .asList(decoder)
      .headOption
```

Still throws me

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PSQLException: ERROR: syntax error at or near "$2"
  Position: 117]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "$2"
  Position: 117
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at com.lucidchart.open.relate.NormalStatementPreparer$class.results(StatementPreparer.scala:90)
	at com.lucidchart.open.relate.Sql$$anon$2.results(SqlQuery.scala:285)
	at com.lucidchart.open.relate.StatementPreparer$class.execute(StatementPreparer.scala:20)
	at com.lucidchart.open.relate.Sql$$anon$2.execute(SqlQuery.scala:285)
	at com.lucidchart.open.relate.Sql$class.asList(SqlQuery.scala:441)
	at com.lucidchart.open.relate.interp.InterpolatedQuery.asList(InterpolatedQuery.scala:8)
	at com.next.user.dao.impl.SessionDao$$anonfun$findBySessionId$1.apply(SessionDao.scala:41)
	at com.next.user.dao.impl.SessionDao$$anonfun$findBySessionId$1.apply(SessionDao.scala:35)
	at play.api.db.DefaultDatabase.withConnection(Databases.scala:155)
	at play.api.db.DefaultDatabase.withConnection(Databases.scala:149)
	at com.next.user.dao.impl.SessionDao$$anonfun$DbFuture$1.apply(SessionDao.scala:20)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
